///////////////////////////////////////////////////////////////////////////////
// RackSorterClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "RackSorterClassFactory.h"
#include "RackSorterServices.h"
#include "RackSorterVersion.h"
#include "RackSorterModule.h"

BEGIN_CLASS_MAP(CRackSorterClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_RackSorterCRackSorterModule, SRVNAME_RACKSORTER "!CRackSorterModule", CRackSorterModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CRackSorterClassFactory::CRackSorterClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_RACKSORTER)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(RackSorter));
#endif //defined(TCDBG_UNIT_VERSION)
}

