///////////////////////////////////////////////////////////////////////////////
// RackSorterServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_RackSorter = 0x3F000000;
#define SRVNAME_RACKSORTER "RackSorter"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_RackSorterCRackSorterModule = {0xcdc0ce8e,0x4cf4,0x4a67,{0x98,0xa1,0xe2,0xd5,0x6f,0xdf,0x8c,0xee}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_RackSorterModuleDefaultAdsPort = 0x00000001;
const PTCID PID_RackSorterModuleCounter = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _RackSorterModuleInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} RackSorterModuleInputs, *PRackSorterModuleInputs;

typedef struct _RackSorterModuleOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} RackSorterModuleOutputs, *PRackSorterModuleOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_RackSorterModuleInputs 0
#define ADI_RackSorterModuleOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
