///////////////////////////////////////////////////////////////////////////////
// RackSorterServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_RackSorter = 0x3F000000;
#define SRVNAME_RACKSORTER "RackSorter"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_RackSorterCRackSorterModule = {0xcdc0ce8e,0x4cf4,0x4a67,{0x98,0xa1,0xe2,0xd5,0x6f,0xdf,0x8c,0xee}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_RackSorterModuleDefaultAdsPort = 0x00000001;
const PTCID PID_RackSorterModuleCounter = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#pragma pack(push,1)
typedef struct _RackSorterModuleInputs
{
	bool x_endSwitch_left;
	bool x_switch_00;
	bool x_switch_01;
	bool x_switch_02;
	bool x_switch_03;
	bool x_switch_04;
	bool x_switch_05;
	bool x_switch_06;
	bool x_switch_07;
	bool x_switch_08;
	bool x_switch_09;
	bool x_endSwitch_right;
	bool y_floorSwitch_00_upstairs;
	bool y_floorSwitch_00_downstairs;
	bool y_floorSwitch_01_upstairs;
	bool y_floorSwitch_01_downstairs;
	bool y_floorSwitch_02_upstairs;
	bool y_floorSwitch_02_downstairs;
	bool y_floorSwitch_03_upstairs;
	bool y_floorSwitch_03_downstairs;
	bool stackerCrane_position_conveyor;
	bool stackerCrane_position_neutral;
	bool stackerCrane_position_stack;
	bool crossbeam_lightBarrier_packet;
	bool conveyor_lightBarrier_packet;
} RackSorterModuleInputs, *PRackSorterModuleInputs;
#pragma pack(pop)

typedef struct _RackSorterModuleOutputs
{
	bool x_motor_left;
	bool x_motor_right;
	bool y_motor_up;
	bool y_motor_down;
	bool z_motor_forward;
	bool z_motor_back;
	bool conveyorAndCrossbeam_motor_forward;
	bool conveyorAndCrossbeam_motor_back;
} RackSorterModuleOutputs, *PRackSorterModuleOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_RackSorterModuleInputs 0
#define ADI_RackSorterModuleOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
