///////////////////////////////////////////////////////////////////////////////
// RackSorterInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "RackSorterServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
